export const ROUTER_STORE = 'routerstore'
export const AUTH_STORE = 'authstore'
export const SNACKBAR_STORE = 'snackbarstore'
export const ADMIN_STORE = 'adminstore'
export const WORKSTATIONS_STORE = 'workstationsstore'
export const UI_STORE = 'uistore'