name: all_non_versioned_push
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Extract Branch Name
        shell: bash
        run: echo "##[set-output name=branch_name;]${GITHUB_REF#refs/heads/}"
        id: extract_branch_name
      - name: Extract Commit Short SHA
        shell: bash
        run: echo "##[set-output name=commit_short_sha;]${GITHUB_SHA::8}"
        id: extract_commit_short_sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: agoracloud/ui-edu:${{ steps.extract_branch_name.outputs.branch_name }}-latest,agoracloud/ui-edu:${{ steps.extract_branch_name.outputs.branch_name }}-${{ steps.extract_commit_short_sha.outputs.commit_short_sha }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
